---
# tasks file for tomcat
- name: Update the System Packages
  apt:
    upgrade: yes
    update_cache: yes
- name: Create a Tomcat User
  user:
    name: tomcat
- name: Create a Tomcat Group
  group:
    name: tomcat
- name: Install JAVA
  apt:  
    name: default-jdk
    state: present
- name: Create a Tomcat Directory
  file:
    path: /opt/tomcat10
    owner: tomcat
    group: tomcat
    mode: 0755
    recurse: yes
- name: download & unarchive tomcat10
  unarchive:
    src: https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.77/bin/apache-tomcat-8.5.77.tar.gz
    dest: /opt/tomcat10
    remote_src: yes
    extra_opts: [--strip-components=1]
- name: Change ownership of tomcat directory
  file:
    path: /opt/tomcat10
    owner: tomcat
    group: tomcat
    mode: "u+rwx,g+rx,o=rx"
    recurse: yes
    state: directory
- name: Changing port
  template:
    src: server.xml.j2
    dest: /opt/tomcat10/conf/server.xml
- name: Creating service for Apache tomcat.
  file:
    path: /etc/systemd/system/tomcat.service
    state: touch
    mode: u+rwx,g-rwx,o-x
- name: download foo.conf
  get_url:
    url: https://raw.githubusercontent.com/aftab70/Apache_Tomcat/master/tomcat_services
    dest: /etc/systemd/system/tomcat.service
- name: Deamon reload.
  command: systemctl daemon-reload
- name: Starting Apache Tomcat service.
  service:
    name: tomcat
    state: started
